default:
  # Dev mode
  DEBUG: false
  # Pathes
  DB_PATH:                        data/db  
  LOG_PATH:                       logs/bot.log
  # Internal parameters
  DATETIME_FORMAT:                '%Y-%m-%d %H:%M:%S'
  # Notification message
  TIMEZONE:                       US/Eastern
  NOTIFICATION_TIME:              '07:00:00'
  NOTIFICATION_UPDATE_INTERVAL:   60*60                 # (1 hour) in seconds
  NOTIFICATION_MESSAGE: >
    PLACEHOLDER
  ADMINS:
    - '@PLACEHOLDER'

production:
  DEBUG: false
  TOKEN:              SECRET_PLACEHOLDER
  CLUB_CHANNEL:       PLACEHOLDER

development:
  DEBUG: true
  TOKEN:              SECRET_PLACEHOLDER
  CLUB_CHANNEL:       PLACEHOLDER  
