[default]
# Pathes
db_path = 'data/db'
log_path = 'logs/bot.log'
# General
timezone = 'US/Eastern'
# Behavior
notification_time = '07:00:00'
notification_update_interval = 3600  # 1 hour (in seconds)
initial_notification_delay = 5       # seconds from now (start)
notification_message = 'PLACEHOLDER'
# Internal parameters
date_format = '%Y-%m-%d'
datetime_format = '%Y-%m-%d %H:%M:%S'
conversation_timeout = 900  # 15 minutes (in seconds)

admins = ['@PLACEHOLDER']

[prod]
debug = false

club_channel = '@PLACEHOLDER'
notification_image = 'PLACEHOLDER'

token = 'SECRET_PLACEHOLDER'

[dev]
debug = true
conversation_timeout = 30   # in seconds

club_channel = '@PLACEHOLDER'
notification_image = 'PLACEHOLDER'

token = 'SECRET_PLACEHOLDER'
